### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by DashaMyagkova** [DashaMyagkova/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by NadiaPol** [comment]
Так, я сам собі! Так, я самостійно зберу і підготую інформацію про кого захочу — про маму чи тата, Ліонеля Мессі чи королеву Вікторію! Може я навіть напишу про себе і тоді в мене це залишиться ще й на потім, для рекрутерів! Звичайно що це буде в рази складніше, аніж просто накопіпастити з готового документу, але я люблю не спати по ночах, що тут такого?
