### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by DashaMyagkova** [DashaMyagkova/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by NadiaPol** [comment]
https://twitter.com/twhiddleston
https://www.instagram.com/twhiddleston/?hl=ru
https://www.facebook.com/twhiddleston
