### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by DashaMyagkova** [DashaMyagkova/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by NadiaPol** [comment]
### Career

_2001–2010: Early work_

Hiddleston began appearing on television, landing parts in Stephen Whittaker's adaptation of Nicholas Nickleby (2001) for ITV, the BBC/HBO co-production Conspiracy (2001), and as Randolph Churchill, the son of Winston Churchill, in the BBC/HBO drama The Gathering Storm (2002).

Hiddleston had leading roles in Declan Donnellan's company Cheek by Jowl's productions The Changeling (2006), and Cymbeline (2007).

Hiddleston was the voiceover for BBC's documentary on the Galapagos Island in 2006.

Hiddleston played the leading role of Edward in Hogg's second feature, Archipelago (2010).

In 2007, he joined a list of British actors, including Kate Winslet and Orlando Bloom, to have guest starred in the long-running medical drama Casualty.

_2011–2014: Career breakthrough_

Hiddleston is well known for his portrayal of Loki in the 2011 Marvel Studios film Thor.

In November 2010, Hiddleston appeared with Benedict Cumberbatch, Gemma Arterton, Eddie Redmayne and Rose Byrne among others in Danny Boyle's one time production of The Children's Monologues.

In 2011, Hiddleston portrayed novelist F. Scott Fitzgerald in writer-director Woody Allen's Midnight in Paris.

On television in 2012, Hiddleston appeared in the BBC Two series The Hollow Crown.

From December 2013 to February 2014, Hiddleston played the title character in William Shakespeare's Coriolanus at the Donmar Warehouse in Covent Garden directed by Josie Rourke.

_2015–present: Varied roles_

Hiddleston replaced Benedict Cumberbatch in the gothic horror film Crimson Peak, directed by Guillermo del Toro in 2015.

In January 2014, Hiddleston became a spokesperson for Jaguar Cars in their "Good to be Bad" ad campaign featuring British actors in villain-themed commercials to promote Jaguar's new models.

In April 2014, Hiddleston starred in another commercial in the campaign, titled "The Art of Villainy".

It was announced in June 2014 that Hiddleston would play country music singer Hank Williams in the 2015 biopic I Saw the Light, based on the 1994 biography.

He reprised his role as Loki in Thor: Ragnarok, released on 3 November 2017, and also appeared in Avengers: Infinity War (2018) and Avengers: Endgame (2019).

In August 2019 he made his Broadway debut reprising his role of Robert in Betrayal

_Upcoming projects_

On 8 November 2018, it was announced that Hiddleston would be reprising his role as Loki in a new Marvel limited series centered on the character which will air on Disney's upcoming streaming service, Disney+.
