### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by DashaMyagkova** [DashaMyagkova/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by NadiaPol** [comment]
**Born**  
9 February 1981 Westminster, London, England

**Alma mater**  
Eton College (secondary)
University of Cambridge
Royal Academy of Dramatic Art

**Occupation**  
Actor

**Zodiac Sign**  
Aquarius

**Food habits**  
non-vegetarian

**Hobbies**  
Singing, listening to music

**Tattoos**  
none

**Favorite Superhero**  Superman
**Favorite Film**  Heat (1995)
**Favorite Food**  Croque Provencal (french), Sushi and Sashimi (Chinese)
**Favorite Color**  Blue, Red
**Favorite Drink**  Jameson on the rocks
**Favorite Country to travel**  Italy
